### ISSUE TITLE
[N400] How to short imports?

### ISSUE THREAD

**Issue by NotFunnyMan** [wemake-services/flake8-broken-line#246]
If I have a long import then how should I short it?
I have this:
```python
from app.baz.bar.foo.first_word.second_word.handler import post as first_word_second_word_scoring
```

And it is longer than 100 symbols in one line. Isort does the following for me:
```python
from app.baz.bar.foo.first_word.second_word.handler import \
    post as first_word_second_word_scoring
```
And I got: `N400: Found backslash that is used for line breaking`

**Comment by sobolevn** [comment]
```python
from app.baz.bar.foo.first_word.second_word.handler import (
    post as first_word_second_word_scoring,
)
```

😉

**Comment by NotFunnyMan** [comment]
Thanks for response :)
Yes. I tried it. But... It conflicts with I001 rule (isort found an import in the wrong position:):

```python
-from app.baz.bar.foo.first_word.second_word.handler import (
-    post as first_word_second_word_scoring,
-)
+from app.baz.bar.foo.first_word.second_word.handler import \
+    post as first_word_second_word_scoring
```

Maybe do you know how to skip it? I mean the suggestion to make import through a line break.

**Comment by sobolevn** [comment]
Use `profile = wemake` or full version: https://github.com/wemake-services/wemake-python-styleguide/blob/9773eb13002cd89c5db6650d7565398f798b224a/setup.cfg#L68-L76
