### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by Secrus** [wemake-services/flake8-broken-line#264]
A recent change made this plugin work with flake8 version 5, but this is still unreleased and actively blocking from migrating to the new flake8 version.

**Comment by fhightower** [comment]
+1

I'm happy to contribute anything needed to get the new version released.

**Comment by kostya-ten** [comment]
+1

**Comment by bellini666** [comment]
+1

**Comment by Secrus** [comment]
> +1
> 
> I'm happy to contribute anything needed to get the new version released.

The work is already done, PR #263 introduced it. The only thing to be done now is the release

**Comment by bellini666** [comment]
@sobolevn can we have a new release for this? (quoting you since you are the one who merged the PR, so I assume you can also do releases here)

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn ,

If you need help with releasing it at [PyPI](https://pypi.org/project/flake8-broken-line/), you can add me as a maintainer at PyPI. My profile: https://pypi.org/user/DmytroLitvinov/

**Comment by sobolevn** [comment]
Hi! New version is released: https://github.com/wemake-services/flake8-broken-line/releases/tag/0.5.0

If any of you want to support further development of this project, consider:
1. https://github.com/sponsors/wemake-services
2. https://opencollective.com/wemake-python-styleguide

🙂

**Comment by DmytroLitvinov** [comment]
@sobolevn , would be nice to see also "one-time payment" via GitHub for [wemake-services](https://github.com/sponsors/wemake-services).

BTW, said "thanks" via opencollective for your great work :muscle:
