### ISSUE TITLE
Compat with flake8 >= 6

### ISSUE THREAD

**Issue by AdrianusWest** [wemake-services/flake8-broken-line#281]
"SolverProblemError

Because flake8-broken-line (0.6.0) depends on flake8 (>=3.5,<6) and no versions of flake8-broken-line match >0.6.0,<0.7.0, flake8-broken-line (>=0.6.0,<0.7.0) requires flake8 (>=3.5,<6). So, because project depends on both flake8 (^6.0.0) and flake8-broken-line (^0.6.0), version solving failed."

**Comment by degenaro** [comment]
Any workaround suggestions until this issue is resolved? Tried removing `flake8-broken-line` from .pre-commit-config.yaml which only led to more complications.

**Comment by sobolevn** [comment]
Sorry, there's nothing I can do. Because `flake8@6` dropped `3.7` support

**Comment by degenaro** [comment]
If flake8 dropped support for 3.7, why not do the same? those who still care can an use old level.

**Comment by AdrianusWest** [comment]
What's the problem with switching to a new version of python anyway?

**Comment by johnthagen** [comment]
For those considering porting to [Ruff](https://beta.ruff.rs/docs/), here is the issue request asking for `flake8-broken-line` to be implemented:

- https://github.com/charliermarsh/ruff/issues/3465

**Comment by terencehonles** [comment]
This should be fixed by #307
